--
-- PostgreSQL database dump
--

-- Dumped from database version 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AlertMessage; Type: TABLE; Schema: public; Owner: raf
--

CREATE TABLE public."AlertMessage" (
    "AlertMessageId" smallint NOT NULL,
    "NodeId" integer NOT NULL,
    "Code" character varying(255),
    "Message" character varying(255),
    "MessageDate" timestamp without time zone NOT NULL,
    "CreatedBy" integer,
    "LastUpdatedBy" integer,
    "CreatedTime" timestamp without time zone,
    "LastUpdatedTime" timestamp without time zone
);


ALTER TABLE public."AlertMessage" OWNER TO raf;

--
-- Name: AlertMessage_AlertMessageId_seq; Type: SEQUENCE; Schema: public; Owner: raf
--

ALTER TABLE public."AlertMessage" ALTER COLUMN "AlertMessageId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AlertMessage_AlertMessageId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- PostgreSQL database dump complete
--

